### ISSUE TITLE
npm update fails at vue-material@1.0.0 postinstall

### ISSUE THREAD

**Issue by michaellass** [joachimdieterich/laravel-curriculum-adminlte3#68]
The README.md suggests to run `npm update` after `npm install` to update all node modules. However, for me this fails with the following error:

```
6126 verbose stack Error: vue-material@1.0.0 postinstall: `sh build/git-hooks/install.sh`
6126 verbose stack spawn ENOENT
6126 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
6126 verbose stack     at ChildProcess.emit (events.js:198:13)
6126 verbose stack     at maybeClose (internal/child_process.js:982:16)
6126 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
6127 verbose pkgid vue-material@1.0.0
6128 verbose cwd /var/www/curriculum/private/laravel-curriculum-adminlte3
6129 verbose Linux 4.19.0-9-amd64
6130 verbose argv "/usr/bin/node" "/usr/bin/npm" "update"
6131 verbose node v10.21.0
6132 verbose npm  v5.8.0
6133 error file sh
6134 error code ELIFECYCLE
6135 error errno ENOENT
6136 error syscall spawn
6137 error vue-material@1.0.0 postinstall: `sh build/git-hooks/install.sh`
6137 error spawn ENOENT
6138 error Failed at the vue-material@1.0.0 postinstall script.
6138 error This is probably not a problem with npm. There is likely additional logging output above.
```

This looks pretty similar to https://github.com/vuematerial/vue-material/issues/1155.

**Comment by joachimdieterich** [comment]
It could be the npm version. I have npm: '6.14.2' installed and could not reproduce this error.
